langganan/urls.py
from django.urls import path

from langganan.views import *

app_name = 'langganan'

urlpatterns = [
    path('', show_langganan_page, name = 'show_langganan_page'),
    path('beli/<str:nama_paket>/<str:dukungan_perangkat>/', show_beli_page, name='show_beli_page'),
    path('beli/<str:nama_paket>/<str:dukungan_perangkat>/bayar/', bayar_paket, name='bayar_paket'),
]

main/urls.py
from django.urls import path, include
from main.views import landing_page, homepage


app_name = 'main'

urlpatterns = [
    path('', homepage, name = 'homepage'),
    path('landing-page/', landing_page, name = "landing-page")
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tayangan/", include("tayangan.urls")),
    path('', include('main.urls')),
    path('authentication/', include('authentication.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('daftar_favorit/', include('daftar_favorit.urls')),
    path('daftar_unduhan/', include('daftar_unduhan.urls')),
    path('daftar-kontributor/', include('daftar_kontributor.urls')),
    path('langganan/', include('langganan.urls')),
]

langganan/models.py
from django.db import models

# Create your models here.

langganan/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .queries import *
from django.views.decorators.csrf import csrf_exempt

def show_langganan_page(request):
    try:
        username = request.COOKIES['username']
    except:
        return HttpResponseRedirect(reverse("authentication:login"))
    daftar_paket_list = daftar_paket()
    daftar_langganan_list = daftar_langganan(username)
    daftar_transaksi_list = daftar_transaksi(username)
    return render(request, "kelola_langganan.html", {'daftar_paket': daftar_paket_list, 
                                                     'daftar_langganan' : daftar_langganan_list,
                                                     'daftar_transaksi' : daftar_transaksi_list})

def show_beli_page(request, nama_paket, dukungan_perangkat):
    try:
        username = request.COOKIES['username']
    except:
        return HttpResponseRedirect(reverse("authentication:login"))
    paket = get_paket(nama_paket, dukungan_perangkat)[0]
    return render(request, "halaman_beli.html", {'paket' : paket})

@csrf_exempt
def bayar_paket(request, nama_paket, dukungan_perangkat):
    try:
        username = request.COOKIES['username']
    except:
        return HttpResponseRedirect(reverse("authentication:login"))
    metode = request.POST.get('metode_pembayaran')
    bayar_paket_post(username, nama_paket, metode)
    return HttpResponseRedirect(reverse("langganan:show_langganan_page"))

langganan/templates/halaman_beli.html
{% extends 'base.html' %}

{% block meta %}
    <title>Beli</title>
{% endblock meta %}

{% block content %}

<div class="container mt-4 p-4 bg-light">
    <div class="mb-5">
        <h2>Halaman Beli</h2>
    </div>
    <label for="exampleFormControlTextarea1" class="form-label fs-5 fw-medium mb-4">Informasi Paket yang Ingin Dibeli:</label>
    <form method="post" action="{% url 'langganan:bayar_paket' paket.nama paket.dukungan_perangkat %}">
        {% csrf_token %}
        <table class="table table-striped table-hover rounded bg-light">
            <thead class="table-light">
            <tr class="text-center">
                <th scope="col">Nama</th>
                <th scope="col">Harga</th>
                <th scope="col">Resolusi Layar</th>
                <th scope="col">Dukungan Perangkat</th>
            </tr>
            </thead>
            <tbody class="text-center">
                <tr>
                    <td>{{ paket.nama }}</td>
                    <td>{{ paket.harga }}</td>
                    <td>{{ paket.resolusi_layar }}</td>
                    <td>{{ paket.dukungan_perangkat }}</td>
                </tr>
            </tbody>
        </table>
        <label for="metode_pembayaran" class="form-label fs-5 fw-medium mb-4">Pilih Metode Pembayaran:</label>
        <select id="metode_pembayaran" name="metode_pembayaran" class="form-select my-4" aria-label="Default select example">
            <option selected>Pilih Metode Pembayaran!</option>
            <option value="Bank Transfer">Transfer Bank</option>
            <option value="Credit Card">Kartu Kredit</option>
            <option value="E-wallet">E-wallet</option>
        </select>
        <button class="btn btn-primary" type="submit">Bayar</button>
    </form>
</div>

{% endblock content %}

langganan/templates/kelola_langganan.html
{% extends 'base.html' %}

{% block meta %}
    <title>Langganan</title>
{% endblock meta %}

{% block content %}
<div class="container mt-4 p-4 bg-light rounded">
    <div class="mb-5">
        <h2 class="bg-light">HALAMAN KELOLA LANGGANAN</h2>
    </div>
    <label for="exampleFormControlTextarea1" class="form-label bg-light fs-5 fw-medium">Paket Langganan Aktif Anda:</label>
    <table class="table rounded bg-light table-striped table-hover">
        <thead class="table-light">
        <tr class="text-center">
            <th scope="col">Nama</th>
            <th scope="col">Harga</th>
            <th scope="col">Resolusi Layar</th>
            <th scope="col">Dukungan Perangkat</th>
            <th scope="col">Tanggal Dimulai</th>
            <th scope="col">Tanggal Akhir</th>
        </tr>
        </thead>
        <tbody class="text-center">
            {% if daftar_langganan %}
              {% for langganan in daftar_langganan %}
                <tr>
                    <td>{{ langganan.nama }}</td>
                    <td>{{ langganan.harga }}</td>
                    <td>{{ langganan.resolusi_layar }}</td>
                    <td>{{ langganan.dukungan_perangkat }}</td>
                    <td>{{ langganan.start_date_time }}</td>
                    <td>{{ langganan.end_date_time }}</td>
                  </tr>
              {% endfor %}
            {% else %}
              <tr>
                  <td colspan="6">No paket found.</td>
              </tr>
            {% endif %}
        </tbody>
      </table>
      <label for="exampleFormControlTextarea1" class="form-label bg-light fs-5 fw-medium">Pilih Paket Lain:</label>
    <table class="table bg-light table-striped table-hover rounded">
        <thead class="table-light">
        <tr class="text-center">
            <th scope="col">Nama</th>
            <th scope="col">Harga</th>
            <th scope="col">Resolusi Layar</th>
            <th scope="col">Dukungan Perangkat</th>
            <th scope="col">Beli</th>
        </tr>
        </thead>
        <tbody class="text-center">
            {% if daftar_paket %}
              {% for paket in daftar_paket %}
                <tr>
                    <td>{{ paket.nama }}</td>
                    <td>{{ paket.harga }}</td>
                    <td>{{ paket.resolusi_layar }}</td>
                    <td>{{ paket.dukungan_perangkat }}</td>
                    <td>
                        <a href="{% url 'langganan:show_beli_page' paket.nama paket.dukungan_perangkat %}" class="btn btn-primary">Beli</a>
                    </td>
                  </tr>
              {% endfor %}
            {% else %}
              <tr>
                  <td colspan="4">No paket found.</td>
              </tr>
            {% endif %}
        </tbody>
      </table>
      <label for="exampleFormControlTextarea1" class="form-label bg-light fs-5 fw-medium">Riwayat Transaksi</label>
    <table class="table bg-light table-striped table-hover rounded">
        <thead class="table-light">
        <tr class="text-center">
            <th scope="col">Nama Paket</th>
            <th scope="col">Tanggal Dimulai</th>
            <th scope="col">Tanggal Akhir</th>
            <th scope="col">Metode Pembayaran</th>
            <th scope="col">Tanggal Pembayaran</th>
            <th scope="col">Total Pembayaran</th>
        </tr>
        </thead>
        <tbody class="text-center">
            {% if daftar_transaksi %}
              {% for transaksi in daftar_transaksi %}
                <tr>
                    <td>{{ transaksi.nama_paket }}</td>
                    <td>{{ transaksi.start_date_time }}</td>
                    <td>{{ transaksi.end_date_time }}</td>
                    <td>{{ transaksi.metode_pembayaran }}</td>
                    <td>{{ transaksi.timestamp_pembayaran }}</td>
                    <td>{{ transaksi.harga }}</td>
                  </tr>
              {% endfor %}
            {% else %}
              <tr>
                  <td colspan="6">No Transaksi found.</td>
              </tr>
            {% endif %}
        </tbody>
      </table>
</div>
<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah ke Daftar Favorit</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div style="text-align: justify;" class="modal-body">
                <p>Selamat! Anda telah berhasil mengunduh 
                    <span class="fw-semibold">
                        Perkenalkan Nama Saya Budiono Siregar
                    </span> 
                    dan akan
                    berlaku hingga 
                    <span class="fw-semibold">
                        09/04/2020
                    </span>
                    . Cek informasi selengkapnya
                    pada halaman daftar unduhan.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                <button type="button" class="btn btn-primary">Ke Daftar Unduhan</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}