daftar_unduhan/urls.py
from django.urls import path, include
from daftar_unduhan.views import *

app_name = 'daftar_unduhan'

urlpatterns = [
    path('show_daftar_unduhan', show_daftar_unduhan, name = 'show_daftar_unduhan'),
    path('tambah_daftar_unduhan', tambah_daftar_unduhan),
    path('delete_unduhan', delete_unduhan, name = 'delete_unduhan'),
    path('add_unduhan/<str:id>', add_unduhan, name = 'add_unduhan')
]

main/urls.py
from django.urls import path, include
from main.views import landing_page, homepage


app_name = 'main'

urlpatterns = [
    path('', homepage, name = 'homepage'),
    path('landing-page/', landing_page, name = "landing-page")
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tayangan/", include("tayangan.urls")),
    path('', include('main.urls')),
    path('authentication/', include('authentication.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('daftar_favorit/', include('daftar_favorit.urls')),
    path('daftar_unduhan/', include('daftar_unduhan.urls')),
    path('daftar-kontributor/', include('daftar_kontributor.urls')),
    path('langganan/', include('langganan.urls')),
]

daftar_unduhan/views.py
from django.shortcuts import render
from .queries import *
from django.db import connection
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

# Create your views here.
def show_daftar_unduhan(request):
    show_download_list = download_list(request)
    return render(request, 'daftar_unduhan.html', {'show_download_list': show_download_list})

def tambah_daftar_unduhan(request):
    return render(request, 'tambah_daftar_unduhan_modal.html')

@csrf_exempt
def delete_unduhan(request):
    username = request.POST.get('username')
    id_tayangan = request.POST.get('id_tayangan')
    try:
        with connection.cursor() as cursor:
            cursor.execute(rf"""SET search_path TO pacilflix;
            DELETE FROM tayangan_terunduh u WHERE u.username = '{username}' AND u.id_tayangan = '{id_tayangan}'
            """)
    except Exception as e:
        messages.error(request, "Unduhan tidak dapat dihapus.")
        return HttpResponseRedirect(reverse('daftar_unduhan:show_daftar_unduhan'))
    
    return HttpResponseRedirect(reverse('daftar_unduhan:show_daftar_unduhan'))

@csrf_exempt
def add_unduhan(request, id: str):
    username = request.COOKIES.get('username')
    # id_tayangan = request.POST.get('id_tayangan')

    with connection.cursor() as cursor:
        cursor.execute(rf"""SET search_path TO pacilflix;
        INSERT INTO tayangan_terunduh(id_tayangan, username, timestamp)
        VALUES ('{id}', '{username}', NOW() );
        """)
    
    return HttpResponseRedirect(reverse('daftar_unduhan:show_daftar_unduhan'))

daftar_unduhan/templates/daftar_unduhan.html
{% extends 'base.html' %}

{% block meta %}
    <title>Daftar Unduhan</title>
{% endblock meta %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="bg-white p-4 rounded shadow">
                <div class="mb-5 text-center">
                    <h2>Daftar Tayangan Unduhan</h2>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover rounded mx-auto">
                        <thead class="table-light">
                            <tr>
                                <th scope="col" colspan="3" class="text-center">{{nama_fav}}</th>
                            </tr>
                            <tr class="text-center">
                                <th scope="col">Judul</th>
                                <th scope="col">Waktu Ditambahkan</th>
                                <th scope="col">Aksi</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            {% if show_download_list %}
                            {% for unduh in show_download_list %}
                                <tr>
                                    <td>{{ unduh.judul }}</td>
                                    <td>{{ unduh.timestamp }}</td>
                                    <td>
                                        <button type="button" class="btn btn-danger delete-button" data-bs-toggle="modal" data-bs-target="#deleteModal" 
                                            data-judul="{{ unduh.judul }}" 
                                            data-username="{{ unduh.username }}" 
                                            data-timestamp="{{ unduh.timestamp }}"
                                            data-id_tayangan="{{ unduh.id_tayangan }}">
                                        Hapus
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="3">Belum ada daftar unduhan.</td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Hapus Judul</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Apakah anda yakin ingin menghapus judul ini dari daftar unduhan?</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'daftar_unduhan:delete_unduhan' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="judul" id="judulToDelete">
                    <input type="hidden" name="username" id="usernameToDelete">
                    <input type="hidden" name="timestamp" id="timestampToDelete">
                    <input type="hidden" name="id_tayangan" id="id_tayanganToDelete">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Error Modal -->
<div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="errorModalLabel">Kesalahan</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Unduhan tidak dapat dihapus karena belum lebih dari 1 hari ditambahkan</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
        var errorModal = new bootstrap.Modal(document.getElementById('errorModal'));
        errorModal.show();
        {% endif %}
        {% endfor %}
        {% endif %}

        $('.delete-button').each(function () {
            $(this).on('click', function () {
                var judul = $(this).data('judul');
                var username = $(this).data('username');
                var timestamp = $(this).data('timestamp');
                var id_tayangan = $(this).data('id_tayangan');
                document.getElementById('judulToDelete').value = judul;
                document.getElementById('usernameToDelete').value = username;
                document.getElementById('timestampToDelete').value = timestamp;
                document.getElementById('id_tayanganToDelete').value = id_tayangan;
            });
        });
    });
</script>
{% endblock content %}

daftar_unduhan/templates/tambah_daftar_unduhan_modal.html
<form action="{% url 'daftar_unduhan:add_unduhan' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="username" id="usernameToRefer">
    <input type="hidden" name="id_tayangan" id="id_tayanganToRefer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
    <button type="submit" class="btn btn-primary add-button">Tambah</button>
</form>

<script>
    $('.add-button').each(function () {
        $(this).on('click', function () {
            var username = $(this).data('username');
            var id_tayangan = $(this).data('id_tayangan');
            document.getElementById('usernameToRefer').value = username;
            document.getElementById('id_tayanganToRefer').value = id_tayangan;
        });
});
</script>
 
<div class="modal fade" id="addDownloadModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah ke Daftar Favorit</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div style="text-align: justify;" class="modal-body">
                <p>Selamat! Anda telah berhasil mengunduh 
                    <span class="fw-semibold">
                        Perkenalkan Nama Saya Budiono Siregar
                    </span> 
                    dan akan
                    berlaku hingga 
                    <span class="fw-semibold">
                        09/04/2020
                    </span>
                    . Cek informasi selengkapnya
                    pada halaman daftar unduhan.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                <button type="button" class="btn btn-primary">Ke Daftar Unduhan</button>
            </div>
        </div>
    </div>
</div>