daftar_favorit/urls.py
from django.urls import path, include
from daftar_favorit.views import *

app_name = 'daftar_favorit'

urlpatterns = [
    path('show_daftar_favorit', show_daftar_favorit, name = 'show_daftar_favorit'),
    path('tambah_daftar_favorit', tambah_daftar_favorit),
    path('delete_favorit', delete_favorit, name = 'delete_favorit'),
    path('delete_favorit_tayangan', delete_favorit_tayangan, name = 'delete_favorit_tayangan'),
    path('show_favorite_details', show_favorite_details, name = 'show_favorite_details'),
    path('add_favorit/<str:id>', add_favorit, name = 'add_favorit')
]

main/urls.py
from django.urls import path, include
from main.views import landing_page, homepage


app_name = 'main'

urlpatterns = [
    path('', homepage, name = 'homepage'),
    path('landing-page/', landing_page, name = "landing-page")
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tayangan/", include("tayangan.urls")),
    path('', include('main.urls')),
    path('authentication/', include('authentication.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('daftar_favorit/', include('daftar_favorit.urls')),
    path('daftar_unduhan/', include('daftar_unduhan.urls')),
    path('daftar-kontributor/', include('daftar_kontributor.urls')),
    path('langganan/', include('langganan.urls')),
]

daftar_favorit/views.py
from django.shortcuts import render
from .queries import *
from django.db import connection
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.
@csrf_exempt
def show_favorite_details(request):
    nama_fav = ""
    username = request.POST.get('username')
    list_judul = request.POST.get('judul')
    time = request.POST.get('timestamp')

    show_details = favorite_details(request, username, list_judul)
    for i in show_details:
        nama_fav = i.get('judul_fav')
        break

    return render(request, "daftar_favorit_list.html", {'show_details': show_details, 'nama_fav':nama_fav })

def show_daftar_favorit(request):
    show_favorite_list = favorite_list(request)
    
    return render(request, "daftar_favorit.html", {'show_favorite_list': show_favorite_list})

def tambah_daftar_favorit(request):
    return render(request, 'tambah_daftar_favorit_modal.html')

@csrf_exempt
def delete_favorit(request):
    username = request.POST.get('username')
    judul = request.POST.get('judul')
    

    with connection.cursor() as cursor:
        cursor.execute(rf"""SET search_path TO pacilflix;
        DELETE FROM daftar_favorit f WHERE f.username = '{username}' AND f.judul = '{judul}'
        """)
    
    return HttpResponseRedirect(reverse('daftar_favorit:show_daftar_favorit'))

@csrf_exempt
def delete_favorit_tayangan(request):
    username = request.POST.get('username')
    id_tayangan = request.POST.get('judul')
    judul_fav = request.POST.get("judul_fav")
    
    with connection.cursor() as cursor:
        # Delete the entry from tayangan_memiliki_daftar_favorit
        cursor.execute(rf"""
        SET search_path TO pacilflix;
        DELETE FROM tayangan_memiliki_daftar_favorit 
        WHERE username = '{username}' 
          AND id_tayangan = '{id_tayangan}' 
          AND timestamp IN (
              SELECT f.timestamp
              FROM tayangan_memiliki_daftar_favorit d
              JOIN daftar_favorit f ON d.username = f.username AND d.timestamp = f.timestamp
              WHERE f.judul = '{judul_fav}'
          )
        """)
    
    show_details = favorite_details(request, username, judul_fav)
    
    return render(request, "daftar_favorit_list.html", {'show_details': show_details }) 

@csrf_exempt
def add_favorit(request, id: str):
    username = request.COOKIES.get('username')
    list_judul = request.POST.get('judul_list_value')

    # print('DBG', id, '+', list_judul)
    with connection.cursor() as cursor:
        cursor.execute(rf"""SET search_path TO pacilflix;
        INSERT INTO daftar_favorit (timestamp, username, judul)
        VALUES (NOW(), '{username}', '{list_judul}' );
        
        INSERT INTO tayangan_memiliki_daftar_favorit (id_tayangan, timestamp, username)
        VALUES ('{id}', NOW(), '{username}');
        """)

    return HttpResponseRedirect(reverse('daftar_favorit:show_daftar_favorit'))

daftar_favorit/templates/daftar_favorit.html
{% extends 'base.html' %}

{% block meta %}
    <title>Daftar Favorit</title>
{% endblock meta %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="bg-white p-4 rounded shadow">
                <div class="mb-5 text-center">
                    <h2>Daftar Favorit</h2>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover rounded mx-auto">
                        <thead class="table-light">
                            <tr>
                                <th scope="col" colspan=3 class="text-center">Daftar Favorit</th>
                            </tr>
                            <tr class="text-center">
                                <th scope="col">Judul</th>
                                <th scope="col">Waktu Ditambahkan</th>
                                <th scope="col">Aksi</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            {% if show_favorite_list %}
                            {% for favorite in show_favorite_list %}
                            <tr>
                                <td>
                                    <form action="{% url 'daftar_favorit:show_favorite_details' %}" method="post" class="d-inline">
                                        {% csrf_token %}
                                        <input type="hidden" name="judul" value="{{ favorite.judul }}">
                                        <input type="hidden" name="username" value="{{ favorite.username }}">
                                        <input type="hidden" name="timestamp" value="{{ favorite.timestamp }}">
                                        <a href="#" class="details-link" onclick="this.closest('form').submit();">{{ favorite.judul }}</a>
                                    </form>
                                </td>
                                <td>{{ favorite.timestamp }}</td>
                                <td>
                                    <button type="button" class="btn btn-danger delete-button" data-bs-toggle="modal" data-bs-target="#deleteModal" 
                                        data-judul="{{ favorite.judul }}" 
                                        data-username="{{ favorite.username }}" 
                                        data-timestamp="{{ favorite.timestamp }}">
                                        Hapus
                                    </button>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="3">Belum ada tayangan favorit.</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Hapus Judul</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Apakah anda yakin ingin menghapus judul ini dari daftar favorit?</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'daftar_favorit:delete_favorit' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="judul" id="judulToDelete">
                    <input type="hidden" name="username" id="usernameToDelete">
                    <input type="hidden" name="timestamp" id="timestampToDelete">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.delete-button').forEach(function(button) {
        button.addEventListener('click', function() {
            var judul = button.getAttribute('data-judul');
            var username = button.getAttribute('data-username');
            var timestamp = button.getAttribute('data-timestamp');
            document.getElementById('judulToDelete').value = judul;
            document.getElementById('usernameToDelete').value = username;
            document.getElementById('timestampToDelete').value = timestamp;
        });
    });
});
</script>
{% endblock content %}

daftar_favorit/templates/daftar_favorit_list.html
{% extends 'base.html' %}

{% block meta %}
    <title>Daftar Favorit</title>
{% endblock meta %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="bg-white p-4 rounded shadow">
                <div class="mb-5 text-center">
                    <h2>Daftar Tayangan List Favorit</h2>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover rounded mx-auto">
                        <thead class="table-light">
                            <tr>
                                <th scope="col" colspan="3" class="text-center">{{nama_fav}}</th>
                            </tr>
                            <tr class="text-center">
                                <th scope="col">Judul</th>
                                <th scope="col">Waktu Ditambahkan</th>
                                <th scope="col">Aksi</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            {% if show_details %}
                            {% for favorite in show_details %}
                            <tr>
                                <td>{{ favorite.judul }}</td>
                                <td>{{ favorite.timestamp }}</td>
                                <td>
                                    <button type="button" class="btn btn-danger delete-button" data-bs-toggle="modal" data-bs-target="#deleteModal" 
                                        data-judul="{{ favorite.id_tayangan }}" 
                                        data-username="{{ favorite.username }}" 
                                        data-timestamp="{{ favorite.timestamp }}"
                                        data-judul_fav="{{ favorite.judul_fav }}">
                                        Hapus
                                    </button>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="3">Belum ada daftar favorit.</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Hapus Judul</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Apakah anda yakin ingin menghapus judul ini dari daftar favorit?</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'daftar_favorit:delete_favorit_tayangan' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="judul" id="judulToDelete">
                    <input type="hidden" name="username" id="usernameToDelete">
                    <input type="hidden" name="timestamp" id="timestampToDelete">
                    <input type="hidden" name="judul_fav" id="judulFavToDelete">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.delete-button').forEach(function(button) {
        button.addEventListener('click', function() {
            var judul = button.getAttribute('data-judul');
            var username = button.getAttribute('data-username');
            var timestamp = button.getAttribute('data-timestamp');
            var judul_fav = button.getAttribute('data-judul_fav');
            document.getElementById('judulToDelete').value = judul;
            document.getElementById('usernameToDelete').value = username;
            document.getElementById('timestampToDelete').value = timestamp;
            document.getElementById('judulFavToDelete').value = judul_fav;
        });
    });
});
</script>
{% endblock content %}

daftar_favorit/templates/tambah_daftar_favorit_modal.html
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addFavoriteModal">
    Tambah
</button>
<div class="modal fade" id="addFavoriteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah ke Daftar Favorit</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Judul daftar favorit</p>
                <select class="form-select" aria-label="Default select example">
                    <option selected>Pilih daftar favoritmu!</option>
                    <option value="1">Galau</option>
                    <option value="2">Happy</option>
                    <option value="3">Badmood</option>
                </select>
            </div>

            <script>
                document.getElementById('form-select').addEventListener('click', function() {
                    var selectElement = document.getElementById('favoriteSelect');
                    var selectedValue = selectElement.value;
                    var selectedText = selectElement.options[selectElement.selectedIndex].text;
                    alert('Selected Value: ' + selectedValue + '\nSelected Text: ' + selectedText);
                });
            </script>

            <div class="modal-footer">
                <form action="{% url 'daftar_favorit:add_favorit' tayangan.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="judul" id="judulToRefer">
                    <input type="hidden" name="username" id="usernameToRefer">
                    <input type="hidden" name="judul_list" id="selectedText">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn btn-primary add-button">Tambah</button>
                </form>
                
            </div>
        </div>
    </div>
</div>

<script>
    $('.add-button').each(function () {
        $(this).on('click', function () {
            // var username = $(this).data('username');
            // var id_tayangan = $(this).data('id_tayangan');
            var judul_list = $(this).data('judul_list');
            // document.getElementById('usernameToRefer').value = username;
            // document.getElementById('id_tayanganToRefer').value = id_tayangan;
            document.getElementById('selectedText').value = judul_list;
        });
});
</script>