authentication/urls.py
from django.urls import path, include
from authentication.views import login_user,logout_user,register


app_name = 'authentication'

urlpatterns = [
    path('login/', login_user, name = 'login'),
    path('register/', register, name = 'register'),
    path('logout/', logout_user, name = 'logout'),
]

main/urls.py
from django.urls import path, include
from main.views import landing_page, homepage


app_name = 'main'

urlpatterns = [
    path('', homepage, name = 'homepage'),
    path('landing-page/', landing_page, name = "landing-page")
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tayangan/", include("tayangan.urls")),
    path('', include('main.urls')),
    path('authentication/', include('authentication.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('daftar_favorit/', include('daftar_favorit.urls')),
    path('daftar_unduhan/', include('daftar_unduhan.urls')),
    path('daftar-kontributor/', include('daftar_kontributor.urls')),
    path('langganan/', include('langganan.urls')),
]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def homepage(request):
    # print(request.COOKIES)
    if 'username' not in request.COOKIES:
        return HttpResponseRedirect(reverse("main:landing-page")) 
    
    context = {
        
    }

    return HttpResponseRedirect(reverse("tayangan:list")) 

def landing_page(request):
    context = {

    }
    return render (request,"landing_page.html",context)

main/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Homepage</title>
    <style>
       

    </style>
{% endblock meta %}

{% block  content%}
<div class="container py-4" style="margin-top: 20px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); background-color: #fff;">
    <h1 style="text-align: center;">Hello there, Enjoy Your Show!</h1>
</div>
{% endblock content %}

main/templates/landing_page.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Welcome Sir!</title>
    <style>
        .container-center  {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 90%;
        }
        .landing {
            background-color: #ffffff;
            color: black;
            padding: 20px;
            border-radius: 10px;
            width: 400px;
            height: auto;
        }
        .landing h1 {
            text-align: center;
            margin-bottom: 20px;
            color: black; /* Warna teks kuning */
        }
        .nav-link {
            color: white;
        }
        
        @media only screen and (max-width: 768px) {
        .container-center {
            margin-right: 0;
            justify-content: center;
        }
        .landing {
            width: 50%;
            height: auto;
        }
        }

    </style>
{% endblock meta %}

{% block auth_navbar %}
    <button class="navbar-toggler ml-auto custom-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ms-auto">
        <li class="nav-item">
            <a class="nav-link" href="/tayangan/trailer">Trailer</a>
        </li>
        <span class="navbar-toggler-icon"></span>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'authentication:login' %}">Login</a>
        </li>
        <span class="navbar-toggler-icon"></span>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'authentication:register' %}">Register</a>
        </li>
        <span class="navbar-toggler-icon"></span>
    </ul>
    </div>
{% endblock auth_navbar %}

{% block  content%}
<div class="container-center">
    <div class="landing">
        <h1>Welcome To PacilFlix D-12</h1>
    </div>
</div>
{% endblock content %}